//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceHistory
    {
        public System.Guid ID_AbsenceHistory { get; set; }
        public string AbsenceMonth { get; set; }
        public Nullable<int> AbsenceYear { get; set; }
        public string NIK { get; set; }
        public string FirstName { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string DayName { get; set; }
        public string ShiftName { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> TimeIN { get; set; }
        public Nullable<System.TimeSpan> TimeOUT { get; set; }
        public string AbsenceStatus { get; set; }
    }
}
