//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityHistory
    {
        public int ID_ActivityHistory { get; set; }
        public string LoginSession { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ActivityTime { get; set; }
    }
}
