//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int ID_Attachment { get; set; }
        public string FileName { get; set; }
        public string MimeType { get; set; }
        public string Extension { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string MD5FileIdentity { get; set; }
        public byte[] FileValue { get; set; }
    }
}
