//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAbsence
    {
        public int ID_DataAbsence { get; set; }
        public string NIK { get; set; }
        public Nullable<System.DateTime> AbsenceDate { get; set; }
        public Nullable<System.TimeSpan> AbsenceTime { get; set; }
        public Nullable<int> Flag { get; set; }
        public string ImportSession { get; set; }
    }
}
