//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Employees1 = new HashSet<Employee>();
            this.UsersEmployees = new HashSet<UsersEmployee>();
            this.EmployeeOnSchedules = new HashSet<EmployeeOnSchedule>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.LeaveRequests1 = new HashSet<LeaveRequest>();
        }
    
        public int ID_Employee { get; set; }
        public string NIK { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public System.DateTime JoinDate { get; set; }
        public Nullable<int> CurrentPosition { get; set; }
        public Nullable<int> CurrentDepartment { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<int> ID_Supervisor { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifedDate { get; set; }
        public Nullable<int> ModifedBy { get; set; }
    
        public virtual ICollection<Employee> Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual ICollection<UsersEmployee> UsersEmployees { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<EmployeeOnSchedule> EmployeeOnSchedules { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests1 { get; set; }
    }
}
