//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportHistory
    {
        public int ID_Import { get; set; }
        public string ImportSession { get; set; }
        public Nullable<System.DateTime> ImportStart { get; set; }
        public Nullable<System.DateTime> ImportEnd { get; set; }
        public Nullable<int> DataImported { get; set; }
        public Nullable<int> DataError { get; set; }
        public Nullable<int> DataExsist { get; set; }
        public Nullable<int> DataUpdated { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string FileSource { get; set; }
    }
}
