//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTitle
    {
        public JobTitle()
        {
            this.Employees = new HashSet<Employee>();
            this.JobTitles1 = new HashSet<JobTitle>();
        }
    
        public int ID_JobTitle { get; set; }
        public string JobTitleName { get; set; }
        public Nullable<int> ParentJobTitle { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<JobTitle> JobTitles1 { get; set; }
        public virtual JobTitle JobTitle1 { get; set; }
    }
}
