//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        public int ID_LeaveRequest { get; set; }
        public Nullable<int> ID_Requestor { get; set; }
        public Nullable<int> ID_Approver { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<int> LeaveCategory { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual LeaveCategories LeaveCategory1 { get; set; }
    }
}
