//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCategories
    {
        public LeaveCategories()
        {
            this.LeaveRequests = new HashSet<LeaveRequest>();
        }
    
        public int ID_LeaveCategory { get; set; }
        public string LeaveCategory { get; set; }
    
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
    }
}
