//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public Shift()
        {
            this.EmployeeOnSchedules = new HashSet<EmployeeOnSchedule>();
            this.ShiftDetails = new HashSet<ShiftDetail>();
        }
    
        public int ID_Shift { get; set; }
        public string ShiftName { get; set; }
        public Nullable<bool> IsNormalDay { get; set; }
        public Nullable<System.TimeSpan> BaseStartTime { get; set; }
        public Nullable<System.TimeSpan> BaseEndTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<EmployeeOnSchedule> EmployeeOnSchedules { get; set; }
        public virtual ICollection<ShiftDetail> ShiftDetails { get; set; }
    }
}
