//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.UserInRoles = new HashSet<UserInRole>();
        }
    
        public int ID_Role { get; set; }
        public string Role { get; set; }
        public string RoleDesc { get; set; }
        public Nullable<int> ParentRole { get; set; }
    
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
    }
}
