//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPSI.AbsenceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInGroup
    {
        public int ID_UserInGroups { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Group { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
